import Head from "next/head";
// import Image from "next/image";
import { Container, Row, Col, Form, Image } from "react-bootstrap";
import { Button, IconButton, ButtonGroup, ButtonToolbar } from "rsuite";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>a linktree Gamer Template</title>
        <meta
          name="influencerTemplate"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        <Container className={styles.container}>
          <Row>
            <Col>
              <Image
                src="/assets/images/profilePic.jpg"
                className={styles.imageBorder}
                fluid
                alt="profilePic"
              />
            </Col>
          </Row>
        </Container>

        {/* Link Grid, Email Slot, */}
        <Container>
          <Row>
            <Col>
              <Button className={styles.buttonColor}>TikTok</Button>
            </Col>
          </Row>
          <Row>
            <Col>
              {" "}
              <Button>Instagram </Button>
            </Col>
          </Row>
          <Row>
            <Col>
              {" "}
              <Button> Twitch</Button>{" "}
            </Col>
          </Row>
          <Row>
            <Col>
              <Button> Patreon </Button>
            </Col>
          </Row>
          <Row>
            <Col>
              <Button>YouTube</Button>
            </Col>
          </Row>
          <Row>
            <Col>
              <Button>SnapChat</Button>
            </Col>
          </Row>

          <Row>
            <Col>
              {" "}
              <Button> Blog </Button>{" "}
            </Col>
          </Row>

          <Row>
            <Col>
              <Button> My Crypto Wallet </Button>
            </Col>
          </Row>

          {/* A link to another page with vides for sale */}
          <Row>
            <Col>
              <Button>Videos</Button>
            </Col>
          </Row>

          <Row>
            <Col>
              <Button> Photos </Button>
            </Col>
          </Row>
        </Container>

        <Container className={styles.container}>
          <Row>
            <Col>
              <Form>
                <Form.Group className="mb-3" controlId="formBasicEmail">
                  <Form.Label>Email address</Form.Label>
                  <Form.Control type="email" placeholder="Enter email" />
                  <Form.Text className="text-muted">
                    We will never share your email with anyone else.
                  </Form.Text>
                </Form.Group>
              </Form>
            </Col>
          </Row>
        </Container>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
